src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\MaxDepth;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * 
 * On déclare que notre entité a des LifecycleCallbacks
 * @ORM\HasLifecycleCallbacks()
 * 
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Un email existe déjà avec ce libellé")
 * @UniqueEntity(
 *     fields={"username"},
 *     message="Un utilisateur existe déjà avec ce libellé")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"api_v1_users","api_v1_users_stat","achievements"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     * @Groups({"api_v1_users","api_v1_users_stat","friends"})
     */
    private $email;


    /**
     * @ORM\Column(type="string", length=255)
     * 
     *@Assert\NotBlank(message="New password can not be blank.")
     * @Assert\Regex(pattern="/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/i",
     *  message="New password is required to be minimum 6 chars in length and to include at least one letter and one number and one special character.")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=64)
     * @Groups({"api_v1_users","friends","achievements"})
     * @Groups({"api_v1_users_stat"})
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     * @Groups({"api_v1_users"})
     */
    private $avatar;

    /**
     * @ORM\Column(type="json", length=64,nullable=true)
     * @Groups({"api_v1_users"})
     */
    private $roles = [];

    /**
     * @ORM\Column(type="boolean")
     * @Groups({"api_v1_users"})
     */
    private $is_active;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"api_v1_users"})
     * @Assert\Type(\DateTime::class)
     * 
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * The people who I think are my friends.
     *

     * @ORM\OneToMany(targetEntity="UserFriends", mappedBy="user")
     * @Groups({"api_v1_users_read","friends"})
     */ 
    private $friends;

    /**
     * The people who think that I’m their friend.
     *
     * @ORM\OneToMany(targetEntity="UserFriends", mappedBy="friend") 
     */
    private $friendsWithMe;

    /**
     * @ORM\ManyToMany(targetEntity=Achievement::class, mappedBy="hadUsers")
     * @Groups({"api_v1_users_read","achievements"})
     *
     */
    private $achievements;


    /**
     * @ORM\OneToMany(targetEntity=Play::class, mappedBy="user", orphanRemoval=true)
     * @Groups({"api_v1_users_stat"})
     */
    private $plays = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $confirmationToken;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_banned;


    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->is_active = false;
        $this->is_banned = false;
        $this->friends = new ArrayCollection();
        $this->friendsWithMe = new ArrayCollection();
        $this->achievements = new ArrayCollection();
        $this->plays = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|UserFriends[]
     */
    public function getFriends(): Collection
    {
        return $this->friends;
    }

    public function addFriend(UserFriends $friend): self
    {
        if (!$this->friends->contains($friend)) {
            $this->friends[] = $friend;
            $friend->setUser($this);
        }

        return $this;
    }

    public function removeFriend(UserFriends $friend): self
    {
        if ($this->friends->contains($friend)) {
            $this->friends->removeElement($friend);
            // set the owning side to null (unless already changed)
            if ($friend->getUser() === $this) {
                $friend->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|UserFriends[]
     */
    public function getFriendsWithMe(): Collection
    {
        return $this->friendsWithMe;
    }

    public function addFriendsWithMe(UserFriends $friendsWithMe): self
    {
        if (!$this->friendsWithMe->contains($friendsWithMe)) {
            $this->friendsWithMe[] = $friendsWithMe;
            $friendsWithMe->setFriend($this);
        }

        return $this;
    }

    public function removeFriendsWithMe(UserFriends $friendsWithMe): self
    {
        if ($this->friendsWithMe->contains($friendsWithMe)) {
            $this->friendsWithMe->removeElement($friendsWithMe);
            // set the owning side to null (unless already changed)
            if ($friendsWithMe->getFriend() === $this) {
                $friendsWithMe->setFriend(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Achievement[]
     */
    public function getAchievements(): Collection
    {
        return $this->achievements;
    }

    public function addAchievement(Achievement $achievement): self
    {
        if (!$this->achievements->contains($achievement)) {
            $this->achievements[] = $achievement;
            $achievement->addHadUser($this);
        }

        return $this;
    }

    public function removeAchievement(Achievement $achievement): self
    {
        if ($this->achievements->contains($achievement)) {
            $this->achievements->removeElement($achievement);
            $achievement->removeHadUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Play[]
     */
    public function getPlays(): Collection
    {
        return $this->plays;
    }

    public function addPlay(Play $play): self
    {
        if (!$this->plays->contains($play)) {
            $this->plays[] = $play;
            $play->setUser($this);
        }

        return $this;
    }

    public function removePlay(Play $play): self
    {
        if ($this->plays->contains($play)) {
            $this->plays->removeElement($play);
            // set the owning side to null (unless already changed)
            if ($play->getUser() === $this) {
                $play->setUser(null);
            }
        }

        return $this;
    }

    public function getConfirmationToken(): ?string
    {
        return $this->confirmationToken;
    }

    public function setConfirmationToken(?string $confirmationToken): self
    {
        $this->confirmationToken = $confirmationToken;

        return $this;
    }

    public function getIsBanned(): ?bool
    {
        return $this->is_banned;
    }

    public function setIsBanned(bool $is_banned): self
    {
        $this->is_banned = $is_banned;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('username')
            ->add('email', EmailType::class)

            ->add('roles', ChoiceType::class
                , [
                    'choices' => [
                        'Utilisateur' => 'ROLE_USER',
                        'Administrateur' => 'ROLE_ADMIN',
                        'SuperAdmin' => "ROLE_SUPER_ADMIN",

                    ],
                    'multiple' => true,
                    'expanded' => true,
                ])

            /* ->add('avatar', FileType::class, [
                'label' => 'avatar',
                'mapped' => true,
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '536k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/x-jpg',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid PDF document',
                    ])
                ],
            ]) */
            ->add('email', EmailType::class, [
                'constraints' => [
                    new Email,
                    new NotBlank,
                ],
            ])
            ->add('password', PasswordType::class, [
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 16,
                    ]),
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Service\ImageUploader;
use App\Service\MailerService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\User;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {


        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/admin", name="admin_index", methods={"GET"})
     */
    public function indexAdmin(UserRepository $userRepository): Response
    {
        return $this->render('admin/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }


    /**
     * @Route("/{id}/profil", name="user_profil", methods={"GET", "POST"})
     */
    public function profil(User $user): Response
    {
        return $this->render('user/profil.html.twig', [
            'user' => $user,
        ]);
    }


    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/banned", name="user_banned", methods={"GET","POST"})
     */
    public function banned(User $user, MailerInterface $mailer,UserRepository $userRepository)
    {

        $mailerService = new MailerService($mailer);
        // I get my entity back
        $user = $this->getDoctrine()->getRepository(User::class)->find($user);
        // I'm asking for the manager.
        $manager = $this->getDoctrine()->getManager();

        $user->setIsBanned(true);

        // I ask the manager to execute in the DB all the modifications that have been made on the entire database.tés
        $manager->flush();
        $to = $user->getEmail();

        
        $mailerService->sendToken($token = [], $to, $user,$tokenLifeTime = [],'Compte banni','user/banned.html.twig');
        
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }
    /**
     * @Route("/{id}/unbanned", name="user_unbanned", methods={"GET","POST"})
     */
    public function unbanned($id)
    {
        // I get my entity back
        $user = $this->getDoctrine()->getRepository(User::class)->find($id);
        // I'm asking for the manager
        $manager = $this->getDoctrine()->getManager();

        $user->setIsBanned(false);
        // I ask the manager to execute in the database all the modifications that have been made on the entitie
        $manager->flush();

        return $this->redirectToRoute('user_index');
    }


    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(UserPasswordEncoderInterface $passwordEncoder, Request $request, User $user): Response
    {
        if($user === $user){
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // We check if the password field contains a va
            // We retrieve the value of this field

            $password = $form->get('password')->getData();

            // If nothing has been typed in the password field, we get the null valu
            // If $password is different from null, we change the password of $user
            if ($password != null) {
                $encodedPassword = $passwordEncoder->encodePassword($user, $password);
                $user->setPassword($encodedPassword);
            }

            /** @var ImageUploader avatar */
            $avatar = $form->get('avatar')->getData();
            if ($avatar) {
                $filename = uniqid() . '.' . $avatar->guessExtension();

                $avatar->move(
                    $this->getParameter('avatar_directory'),
                    $filename
                );

                $user->setAvatar($filename);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index');
        }else('vous ne pouvez pas modifié ce profil');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }



}

templates/user/_form.html.twig
{{ form_start(form) }}

    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/banned.html.twig
{% block body %}
    <h3>Votre compte a été banni</h3>
<p>Votre compte {{username.username}} a été banni sur O'troquet pour comportement inadapté.</p>

<p>Veuillez contacter un administrateur pour plus d'informations.</p>
{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }} - Modifier l'utilisateur
{% endblock %}

{% block body %}
    <h1 class="mt-5">Modifier l'utilisateur</h1>
    {% if "ROLE_SUPER_ADMIN" in app.user.roles %}
    {{ form_start(form) }}
    {{ form_row(form.username) }}
    {{ form_row(form.email) }}
    {{ form_row(form.password) }}
    {{ form_row(form.roles) }}
    {% elseif "ROLE_ADMIN" in app.user.roles  %}
    {{ form_row(form.username) }}
    {{ form_row(form.email) }}
    {{ form_row(form.password) }}
    {{ form_row(form.roles) == false }}
    {% endif %}


    <button class="btn btn-primary" type="submit">Valider</button>
    <a href="{{ path('user_show', {'id': user.id}) }}" class="btn btn-link">Annuler</a>
    {{ form_end(form) }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des utilisateurs{% endblock %}

{% block body %}

    <h1>Liste des utilisateurs</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Role</th>
            <th>Statut</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
        {% if ("ROLE_SUPER_ADMIN" not in user.roles) and ("ROLE_ADMIN" not in user.roles) %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>

                {% if ("ROLE_ADMIN" in user.roles ? user.roles|json_encode : ''  ) %}

                <td>Adminstrateur</td>   
                {% else %}
                <td>Utilisateur</td>
                {% endif %}
                <td>{% if user.isBanned %}
                    {{ ' Banni' | trans({}, 'false') }} 
                    {% else %}
                    {{ 'Autorisé' | trans({}, 'true') }}
                    {% endif%}
                </td>
                <td>
                    {% if user.isBanned == false %}
                        <a href="{{ path('user_banned', {'id': user.id}) }}" class="badge badge-danger" onclick="return confirm('Etes vous sur de vouloir bannir l\'utilisateur')">
                            Bannir
                        </a>
                    {% elseif user.isBanned == true  %}
                        <a href="{{ path('user_unbanned', {'id': user.id}) }}" class="badge badge-success"onclick="return confirm('Etes vous sur de vouloir réautorisé l\'utilisateur')">
                            Autoriser
                        </a>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}" class="badge badge-primary" >Détail</a>
                </td>
                <td>

            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Crée un nouvelle utilisateur</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>{{ user.username }}</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Username</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Roles</th>

            {% if ("ROLE_ADMIN" in user.roles ? user.roles|json_encode : ''  ) %}
                <td>Adminstrateur</td>
            {% else %}
                <td>Utilisateur</td>
            {% endif %}
        </tr>
        </tbody>
    </table>


    <a href="{{ path('user_edit', {'id': user.id}) }}" class="btn btn-warning">
        Modifier
    </a>
    {#<a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>#}

{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>{{ user.username }}</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ user.id }}</td>
        </tr>
        <tr>
            <th>Username</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Roles</th>
            {{(user.roles ? user.roles|json_encode : '' )}}
            {% if ("ROLE_ADMIN" in user.roles ? user.roles|json_encode : ''  ) %}
                <td>Adminstrateur</td>
            {% else %}
                <td>Utilisateur</td>
            {% endif %}
        </tr>
        </tbody>
    </table>


    <a class="btn btn-primary" href="{{ path('user_index') }}">Back to list</a>
    {% if user.isBanned == false %}
        <a href="{{ path('user_banned', {'id': user.id}) }}" class="btn btn-danger" onclick="return confirm('Etes vous sur de vouloir bannir l'utilisateur')">
            Bannir
        </a>
    {% elseif user.isBanned == true  %}
        <a href="{{ path('user_unbanned', {'id': user.id}) }}" class="btn btn-success" onclick="return confirm('Etes vous sur de vouloir réautorisé l'utilisateur')">
            Réautorisé
        </a>
    {% endif %}
    <a href="{{ path('user_edit', {'id': user.id}) }}" class="btn btn-warning">
        Modifier
    </a>
    {#<a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>#}

{% endblock %}